name: Grow
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare your file
      run: |
        mkdir download
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        drive=`git log --pretty=format: -1 --name-only *.md`
        export drive
        cd ..
        wget -q `cat $wiki/$drive | xargs` --directory-prefix=download
    - name: Archive files
      run: |
        sudo apt-get update
        sudo apt-get install zip
        zip -r archive.zip download


    - name: Upload README.md to Google Drive
      uses: Jodebu/upload-to-drive@master
      with:
        target: archive.zip
        credentials: ${{ secrets.CREDENTIALS }}
        folder: ${{ secrets.FOLDER_ID }}

    - name: Where are we
      run: |
        pwd 
        ls
